version: '3'

services:
  registry:
    image: registry:2
    restart: always
    container_name: thinkimi_registry
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/auth:/auth"
      - "./volumes/data:/var/lib/registry"
    environment:
      VIRTUAL_HOST: registry.thinkimi.com
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: registry.thinkimi.com
      LETSENCRYPT_EMAIL: kimi@thinkimi.com
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm

networks:
  default:
    external:
      name: thinkimi-networks
