version: '3'

services:
  registry:
    image: registry
    restart: always
    container_name: thinkimi_registry
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes:/etc/docker/registry/"
      - "./volumes/data:/var/lib/registry"
    environment:
      VIRTUAL_HOST: registry.thinkimi.com
      VIRTUAL_PORT: 445
      LETSENCRYPT_HOST: registry.thinkimi.com
      LETSENCRYPT_EMAIL: kimi@thinkimi.com

networks:
  default:
    external:
      name: thinkimi-networks
